# Generated by Django 2.1 on 2018-08-15 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specification', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('PRC', 'Processadores'), ('M.R', 'Memória Ram'), ('D.R', 'Disco Rígido/SSD'), ('P.V', 'Placa de Vídeo'), ('GBT', 'Gabinete'), ('P.M', 'Placa Mãe'), ('F.T', 'Fonte')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loja.Product')),
                ('total', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
