# Generated by Django 2.1 on 2018-08-18 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_auto_20180817_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('DIN', 'Dinheiro'), ('CHE', 'Cheque'), ('CTC', 'Cartão de Crédito'), ('CTD', 'Cartão de Débito')], max_length=3)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('P.R', 'Pedido Realizado'), ('S.E', 'Separação em Estoque'), ('MTG', 'Em montagem'), ('R.T', 'Realização de testes')], default='P.R', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Order'),
        ),
    ]
