# Generated by Django 2.1 on 2018-08-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_auto_20180818_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('P.A', 'Pedido Aberto'), ('P.R', 'Pedido Realizado'), ('S.E', 'Separação em Estoque'), ('MTG', 'Em montagem'), ('R.T', 'Realização de testes')], default='P.A', max_length=3),
        ),
    ]
